apiVersion: v1
kind: ConfigMap
metadata:
  name: previewforge-prometheus
data:
  prometheus.yml: |
{{ .Files.Get "prometheus/prometheus.yml" | indent 4 }}
  rules.yml: |
{{ .Files.Get "alerts/rules.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: previewforge-grafana
data:
  grafana.ini: |
{{ .Files.Get "grafana/grafana.ini" | indent 4 }}
  datasources.yml: |
{{ .Files.Get "grafana/datasources.yml" | indent 4 }}
  dashboards.yml: |
{{ .Files.Get "grafana/dashboards.yml" | indent 4 }}
  previewforge.json: |
{{ .Files.Get "grafana/previewforge.json" | indent 4 }}
