apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}-quota
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "6"
    limits.memory: 3Gi
    pods: "10"
    persistentvolumeclaims: "2"
